export enum RequestStatus { NEW='NEW', SUBMITTED='SUBMITTED', EXPERT_ASSIGNED='EXPERT_ASSIGNED', DOCUMENTS_PENDING='DOCUMENTS_PENDING', IN_PROGRESS='IN_PROGRESS', REVIEW='REVIEW', COMPLETED='COMPLETED' }
export enum Priority { TODAY='TODAY', THIS_WEEK='THIS_WEEK', FLEXIBLE='FLEXIBLE' }
export enum DocStatus { UPLOADED='UPLOADED', APPROVED='APPROVED', REJECTED='REJECTED' }
export enum BookingStatus { CONFIRMED='CONFIRMED', CANCELLED='CANCELLED', COMPLETED='COMPLETED', RESERVED='RESERVED', PENDING='PENDING' }
